[2021-03-06 18:02:00,577] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: nhunh_example.zenodo_downloader 2021-03-06T18:02:00.257398+00:00 [queued]>
[2021-03-06 18:02:00,591] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: nhunh_example.zenodo_downloader 2021-03-06T18:02:00.257398+00:00 [queued]>
[2021-03-06 18:02:00,591] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-06 18:02:00,592] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-06 18:02:00,592] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-06 18:02:00,601] {taskinstance.py:1063} INFO - Executing <Task(ZenodoDownloaderOperator): zenodo_downloader> on 2021-03-06T18:02:00.257398+00:00
[2021-03-06 18:02:00,608] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nhunh_example', 'zenodo_downloader', '2021-03-06T18:02:00.257398+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/airflow_example.py', '--cfg-path', '/tmp/tmpxiwweuz0', '--error-file', '/tmp/tmpjiq0jndu']
[2021-03-06 18:02:00,608] {standard_task_runner.py:77} INFO - Job 4: Subtask zenodo_downloader
[2021-03-06 18:02:00,605] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2021-03-06 18:02:00,649] {logging_mixin.py:104} INFO - Running <TaskInstance: nhunh_example.zenodo_downloader 2021-03-06T18:02:00.257398+00:00 [running]> on host 2ca80f9c51df
[2021-03-06 18:02:00,716] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nunovazafonso
AIRFLOW_CTX_DAG_ID=nhunh_example
AIRFLOW_CTX_TASK_ID=zenodo_downloader
AIRFLOW_CTX_EXECUTION_DATE=2021-03-06T18:02:00.257398+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-06T18:02:00.257398+00:00
[2021-03-06 18:02:00,716] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-06 18:02:00,717] {bash.py:158} INFO - Running command: 
		        echo 'Starting URLs download'
		        zenodo_get -o /home/nunovazafonso/Documents/Projects/udacity/capstone-project/dataeng_capstone/input/data/ -w flights_list 4485741
		        zenodo_get -o /home/nunovazafonso/Documents/Projects/udacity/capstone-project/dataeng_capstone/input/data/ -w twitter_list 4568860
		        echo 'Finished URLs download'

				cd /home/nunovazafonso/Documents/Projects/udacity/capstone-project/dataeng_capstone/input/data/

		        # Demo purposes select only a few lines
        		head -2 flights_list > flights
		        head -10 twitter_list > tweets

    		    echo "Starting file downloads"

        		echo 'Starting flight data download'
        		wget -i flights

		        echo 'Starting tweet data download'
        		wget -i tweets

		        echo 'Finished file downloads' 
[2021-03-06 18:02:00,730] {bash.py:169} INFO - Output:
[2021-03-06 18:02:00,742] {bash.py:173} INFO - Starting URLs download
[2021-03-06 18:02:00,743] {bash.py:173} INFO - bash: line 2: zenodo_get: command not found
[2021-03-06 18:02:00,745] {bash.py:173} INFO - bash: line 3: zenodo_get: command not found
[2021-03-06 18:02:00,745] {bash.py:173} INFO - Finished URLs download
[2021-03-06 18:02:00,745] {bash.py:173} INFO - bash: line 6: cd: /home/nunovazafonso/Documents/Projects/udacity/capstone-project/dataeng_capstone/input/data/: No such file or directory
[2021-03-06 18:02:00,747] {bash.py:173} INFO - head: cannot open 'flights_list' for reading: No such file or directory
[2021-03-06 18:02:00,749] {bash.py:173} INFO - head: cannot open 'twitter_list' for reading: No such file or directory
[2021-03-06 18:02:00,749] {bash.py:173} INFO - Starting file downloads
[2021-03-06 18:02:00,749] {bash.py:173} INFO - Starting flight data download
[2021-03-06 18:02:00,749] {bash.py:173} INFO - bash: line 15: wget: command not found
[2021-03-06 18:02:00,750] {bash.py:173} INFO - Starting tweet data download
[2021-03-06 18:02:00,750] {bash.py:173} INFO - bash: line 18: wget: command not found
[2021-03-06 18:02:00,750] {bash.py:173} INFO - Finished file downloads
[2021-03-06 18:02:00,751] {bash.py:177} INFO - Command exited with return code 0
[2021-03-06 18:02:00,783] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=nhunh_example, task_id=zenodo_downloader, execution_date=20210306T180200, start_date=20210306T180200, end_date=20210306T180200
[2021-03-06 18:02:00,818] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-06 18:02:00,862] {local_task_job.py:146} INFO - Task exited with return code 0
